### ISSUE TITLE
Shouldn't catch CommandSyntaxException

### ISSUE THREAD

**Issue by Geek202** [P03W/Aegis#3]
Aegis currently [wraps the function passed to `executes` with a try-catch](https://github.com/P03W/Aegis/blob/master/src/main/kotlin/com/github/P03W/aegis/Aegis.kt#L468-L475) to print the stacktrace of exceptions if debug is enabled, however this causes `CommandSyntaxException`s to not be passed higher up and display the proper error message they contain to the user. `CommandSyntaxException` is commonly used with classes such as `SimpleCommandExceptionType` and `DynamicCommandExceptionType` to easily implement error messages in both mods and vanilla itself, and so should be handled like it would in vanilla.

This could be fixed by modifying the `executes` method to rethrow `CommandSyntaxExption`s like this:
```kotlin
    fun executesExplicit(debug: Boolean = false, method: (CommandContext<ServerCommandSource>)->Int) {
        chainHasExecute = true
        currentNode.executes {
            try {
                method(it)
            } catch (e: CommandSyntaxException) {
                throw e
            } catch (possible: Throwable) {
                if (debug) {
                    possible.printStackTrace()
                }
                0
            }
        }
    }

```

**Comment by P03W** [comment]
Ah, didn't expect that problem, will fix that ASAP

**Comment by Geek202** [comment]
Thanks 😃
